// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYhg5JF1SQ1QiVot_PqBtCiTqvoJr2GQ',
    appId: '1:1070793690217:android:4280158e1f13de33f626f8',
    messagingSenderId: '1070793690217',
    projectId: 'emoney-9799b',
    storageBucket: 'emoney-9799b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdELHiUEkNGcEdt2Lgtowd4s8tT40iGQ',
    appId: '1:1070793690217:ios:1c39de3ccf4bef72f626f8',
    messagingSenderId: '1070793690217',
    projectId: 'emoney-9799b',
    storageBucket: 'emoney-9799b.firebasestorage.app',
    iosBundleId: 'com.example.dompetGlobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb_yNvCFuB-l1G85HXrFQ2C8lr-NUAnzs',
    appId: '1:1070793690217:web:63e96e5da8d7ee07f626f8',
    messagingSenderId: '1070793690217',
    projectId: 'emoney-9799b',
    authDomain: 'emoney-9799b.firebaseapp.com',
    storageBucket: 'emoney-9799b.firebasestorage.app',
    measurementId: 'G-JM33L35QPB',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_yNvCFuB-l1G85HXrFQ2C8lr-NUAnzs',
    appId: '1:1070793690217:web:63e96e5da8d7ee07f626f8',
    messagingSenderId: '1070793690217',
    projectId: 'emoney-9799b',
    authDomain: 'emoney-9799b.firebaseapp.com',
    storageBucket: 'emoney-9799b.firebasestorage.app',
    measurementId: 'G-JM33L35QPB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdELHiUEkNGcEdt2Lgtowd4s8tT40iGQ',
    appId: '1:1070793690217:ios:1c39de3ccf4bef72f626f8',
    messagingSenderId: '1070793690217',
    projectId: 'emoney-9799b',
    storageBucket: 'emoney-9799b.firebasestorage.app',
    iosBundleId: 'com.example.dompetGlobal',
  );
}
